### ISSUE TITLE
Testing appears broken

### ISSUE THREAD

**Issue by MorganRodgers** [OSC/osc_machete_rails#65]
`bundle exec rake test` fails with an error about the SQLite gem not being loaded.

**Comment by johrstrom** [comment]
I can confirm. Here's the stack I get with the middle bit removed for brevity. You can see it's a from initializing this dummy environment.

```bash
	34: from /home/jeff/.gem/ruby/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `<main>'
	33: from /home/jeff/.gem/ruby/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:5:in `select'
	32: from /home/jeff/.gem/ruby/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `block in <main>'
	31: from /home/jeff/.gem/ruby/gems/rake-13.0.1/lib/rake/rake_test_loader.rb:17:in `require'
	30: from /work/test/integration/error_handling_test.rb:1:in `<top (required)>'
	29: from /work/test/integration/error_handling_test.rb:1:in `require'
	28: from /work/test/test_helper.rb:5:in `<top (required)>'
	27: from /work/test/test_helper.rb:5:in `require'
	26: from /work/test/dummy/config/environment.rb:5:in `<top (required)>'
	25: from /home/jeff/.gem/ruby/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `method_missing'
	24: from /home/jeff/.gem/ruby/gems/railties-4.2.11.1/lib/rails/railtie.rb:194:in `public_send'
	23: from /home/jeff/.gem/ruby/gems/railties-4.2.11.1/lib/rails/application.rb:352:in `initialize!'
	22: from /home/jeff/.gem/ruby/gems/railties-4.2.11.1/lib/rails/initializable.rb:54:in `run_initializers'

.....
	 3: from /home/jeff/.gem/ruby/gems/activerecord-4.2.11.1/lib/active_record/railtie.rb:122:in `block (2 levels) in <class:Railtie>'
	 2: from /home/jeff/.gem/ruby/gems/activerecord-4.2.11.1/lib/active_record/connection_handling.rb:50:in `establish_connection'
	 1: from /home/jeff/.gem/ruby/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/connection_specification.rb:174:in `spec'
/home/jeff/.gem/ruby/gems/activerecord-4.2.11.1/lib/active_record/connection_adapters/connection_specification.rb:177:in `rescue in spec': Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
rake aborted!
```
